version: "3.8"

services:
    client:
        build:
            dockerfile: ./packages/client/Dockerfile
            context: .
            args:
                REACT_APP_API_URL: ${REACT_APP_API_URL}
        depends_on:
            - api
        env_file: ./envs/.docker.env
        ports:
            - ${CLIENT_PORT}:${CLIENT_PORT}

    api:
        build:
            dockerfile: ./packages/api/Dockerfile
            context: .
        depends_on:
            - postgres
            - redis
        env_file: ./envs/.docker.env
        environment:
            - POSTGRES_HOST=postgres
        ports:
            - ${API_PORT}:${API_PORT}
        networks:
            - api-network

    postgres:
        image: postgres:12
        env_file: ./envs/.docker.env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        networks:
            - api-network

    redis:
        image: redis
        ports:
            - ${REDIS_PORT}:${REDIS_PORT}
        networks:
            - api-network

networks:
    api-network:
        driver: bridge
